name: $(BuildDefinitionName)_[$(Date:ddMMyyyy)]

pool:
  vmImage: 'Ubuntu 18.04'

container: gr00vysky/docker-arm-api:latest

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

steps:
- script: /start.sh