name: $(BuildDefinitionName)_[$(Date:ddMMyyyy)]

pool:
  vmImage: 'ubuntu-16.04'

container: gr00vysky/docker-arm-api:latest

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

steps:
- script: printenv